# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
version: 2.1
orbs:
  aws-cli: circleci/aws-cli@5.1.0
jobs:
  build:
    environment:
      AWS_REGION: us-east-1
      BASE_VERSION: 1.0.
    docker:
      - image: dpmcgarry/esp-idf:latest
    resource_class: dizon/onprem
    steps:
      - checkout
      - run:
          name: List Home
          command: ls -la -R ~
      - run:
          name: Print Working Directory
          command: pwd
      - aws-cli/setup:
          profile_name: default
          region: ${AWS_REGION}
          role_arn: ${AWS_ROLE_ARN}
workflows:
  build-and-upload:
    jobs:
      - build
